In [1]:
# Loading + inspection of data before cleaning, filtering.

In [2]:
# Read_csv - loading with right options
import pandas as pd
df_metrics = pd.read_csv(
    "server_metrics.csv", 
    parse_dates = ["timestamp"],
    dtype = {"server_id" : "category"},
    na_values = ["N/A", "null", "-"]
)
print("shows exact columns names :", df_metrics.columns.tolist(), "\n")
# head() and tail() - first and last look
print("top 5 rows of df_metrics\n", df_metrics.head())
print("last 5 rows of df_metrics\n", df_metrics.tail())

shows exact columns names : ['timestamp', 'server_id', 'cpu_pct', 'memory_pct', 'response_ms', 'disk_pct', 'status']

top 5 rows of df_metrics
    timestamp server_id  cpu_pct  memory_pct  response_ms  disk_pct status
0 2026-01-01    srv-01     49.6        94.6        891.8      68.9     ok
1 2026-01-01    srv-02     32.3        33.9       1046.1      69.1     ok
2 2026-01-01    srv-03     21.6        96.0       1007.3      43.8     ok
3 2026-01-01    srv-04     34.5        50.7        653.5      58.1     ok
4 2026-01-01    srv-05     68.3        39.5        386.0      53.8     ok
last 5 rows of df_metrics
               timestamp server_id  cpu_pct  memory_pct  response_ms  disk_pct  \
495 2026-01-05 03:00:00    srv-01     88.7        38.9        959.1      38.1
496 2026-01-05 03:00:00    srv-02     41.8        89.6       1135.6      39.7
497 2026-01-05 03:00:00    srv-03     97.5        62.9       1043.1      68.3
498 2026-01-05 03:00:00    srv-04     42.6        43.8        926.1      55.1
499 2026-01-05 03:00:00    srv-05     58.9        69.3       1045.4      93.7

      status
495  warning
496       ok
497       ok
498       ok
499       ok

In [3]:
# head()  0 see the structure
df_metrics.head()

   timestamp server_id  cpu_pct  memory_pct  response_ms  disk_pct status
0 2026-01-01    srv-01     49.6        94.6        891.8      68.9     ok
1 2026-01-01    srv-02     32.3        33.9       1046.1      69.1     ok
2 2026-01-01    srv-03     21.6        96.0       1007.3      43.8     ok
3 2026-01-01    srv-04     34.5        50.7        653.5      58.1     ok
4 2026-01-01    srv-05     68.3        39.5        386.0      53.8     ok

In [4]:
# shape - know the size
print(df_metrics.shape)

(500, 7)

In [5]:
# info() - inspection command - dtype - nulls
df_metrics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    500 non-null    datetime64[ns]
 1   server_id    500 non-null    category
 2   cpu_pct      500 non-null    float64
 3   memory_pct   500 non-null    float64
 4   response_ms  500 non-null    float64
 5   disk_pct     500 non-null    float64
 6   status       500 non-null    object
dtypes: category(1), datetime64[ns](1), float64(4), object(1)
memory usage: 24.1+ KB

In [6]:
# describe() - gives stastical summary
df_metrics.describe()

                 timestamp     cpu_pct  memory_pct  response_ms    disk_pct
count                  500  500.000000  500.000000   500.000000  500.000000
mean   2026-01-03 01:30:00   60.027400   63.355000   625.533600   62.412800
min    2026-01-01 00:00:00   20.600000   30.200000    51.800000   30.300000
25%    2026-01-02 00:45:00   39.000000   45.075000   335.950000   46.700000
50%    2026-01-03 01:30:00   60.900000   64.300000   633.700000   62.300000
75%    2026-01-04 02:15:00   81.300000   80.125000   908.125000   78.625000
max    2026-01-05 03:00:00   98.600000   98.000000  1196.400000   94.800000
std                    NaN   23.464233   20.007543   325.294967   18.823192

In [7]:
# isnull().sum() For percentage of nulls per column - null map
df_metrics.isnull().sum()

timestamp      0
server_id      0
cpu_pct        0
memory_pct     0
response_ms    0
disk_pct       0
status         0
dtype: int64

In [8]:
# value_counts() - category distribution
df_metrics["server_id"].value_counts()

server_id
srv-01    100
srv-02    100
srv-03    100
srv-04    100
srv-05    100
Name: count, dtype: int64

In [9]:
# statue distribution across fleet of servers
df_metrics["status"].value_counts(normalize=True).mul(100).round(1)
# NOrmalize gives percentages

status
ok          76.6
warning     17.8
critical     5.6
Name: proportion, dtype: float64

In [10]:
# nuniquye() - unique value counts
df_metrics.nunique()

timestamp      100
server_id        5
cpu_pct        371
memory_pct     356
response_ms    495
disk_pct       354
status           3
dtype: int64

In [11]:
# time range
df_metrics["timestamp"].agg(["min", "max"])

min   2026-01-01 00:00:00
max   2026-01-05 03:00:00
Name: timestamp, dtype: datetime64[ns]

In [12]:
# sample() - random cross section
df_metrics.sample(5) # 5 random rows
df_metrics.sample(frac=0.01) # 1 percent random sample

,timestamp,server_id,cpu_pct,memory_pct,response_ms,disk_pct,status
83,2026-01-01 16:00:00,srv-04,55.4,49.9,428.0,73.7,warning
494,2026-01-05 02:00:00,srv-05,38.0,95.6,1095.9,76.9,ok
100,2026-01-01 20:00:00,srv-01,75.2,66.5,406.0,82.9,ok
292,2026-01-03 10:00:00,srv-03,51.1,74.3,172.6,72.8,critical
280,2026-01-03 08:00:00,srv-01,33.2,41.4,92.2,77.9,ok

In [13]:
# check column names - tolist()
df_metrics = pd.read_csv("server_metrics.csv")
print(df_metrics.columns.tolist())

['timestamp', 'server_id', 'cpu_pct', 'memory_pct', 'response_ms', 'disk_pct', 'status']

In [14]:
# Loading data, write to postgreSQL and read back required data through sql query in pandas. No CSV export needed.

import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("server_metrics.csv")
df["timestamp"] = pd.to_datetime(df["timestamp"])

engine = create_engine("postgresql://postgres:postgres@localhost:5432/postgres")

df.to_sql("server_metrics", engine, if_exists="replace", index=False)
#if_exists="replace" drops and recreates the table every run 

df_output = pd.read_sql("""
    SELECT server_id, timestamp, cpu_pct, memory_pct, response_ms
    FROM server_metrics
    WHERE timestamp >= (
        SELECT MAX(timestamp) - INTERVAL '7 days'
        FROM server_metrics
    )
""", engine)
print(df_output.dtypes)
print(f"shape : {df_output.shape}")
print(f"Date range : {df_output['timestamp'].min()} to {df_output['timestamp'].max()}")
print(f"Row count : {len(df_output)}")
print(f"Max CPU : {df_output['cpu_pct'].max()}")
print(df_output.head())

server_id              object
timestamp      datetime64[ns]
cpu_pct               float64
memory_pct            float64
response_ms           float64
dtype: object
shape : (500, 5)
Date range : 2026-01-01 00:00:00 to 2026-01-05 03:00:00
Row count : 500
Max CPU : 98.6
  server_id  timestamp  cpu_pct  memory_pct  response_ms
0    srv-01 2026-01-01     49.6        94.6        891.8
1    srv-02 2026-01-01     32.3        33.9       1046.1
2    srv-03 2026-01-01     21.6        96.0       1007.3
3    srv-04 2026-01-01     34.5        50.7        653.5
4    srv-05 2026-01-01     68.3        39.5        386.0

In [15]:
# Task - Load server_metrics.csv correctly — with parse_dates, dtype for server_id as category, and na_values handling. Print info() and confirm server_id dtype is category.
df_metrics = pd.read_csv(
    "server_metrics.csv", 
    parse_dates =["timestamp"],
    dtype={"server_id" : "category"},
    na_values=["N/A", "null", "-"]
)

df_metrics.info()
print(df_metrics["server_id"].dtype)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    500 non-null    datetime64[ns]
 1   server_id    500 non-null    category
 2   cpu_pct      500 non-null    float64
 3   memory_pct   500 non-null    float64
 4   response_ms  500 non-null    float64
 5   disk_pct     500 non-null    float64
 6   status       500 non-null    object
dtypes: category(1), datetime64[ns](1), float64(4), object(1)
memory usage: 24.1+ KB
category

In [16]:
# Task - Run the full triage protocol on df_metrics — all 8 commands. For each one write a one-line comment above it explaining what you're checking.
df_metrics.head()

   timestamp server_id  cpu_pct  memory_pct  response_ms  disk_pct status
0 2026-01-01    srv-01     49.6        94.6        891.8      68.9     ok
1 2026-01-01    srv-02     32.3        33.9       1046.1      69.1     ok
2 2026-01-01    srv-03     21.6        96.0       1007.3      43.8     ok
3 2026-01-01    srv-04     34.5        50.7        653.5      58.1     ok
4 2026-01-01    srv-05     68.3        39.5        386.0      53.8     ok

In [17]:
df_metrics.shape               # confirm expected row count
df_metrics.info()              # displays dtypes and null check
df_metrics.describe()          # gives fleet-wide statistical range column wise
# gives per server stastical breakdwon
df_metrics.isnull().sum() 
df_metrics.nunique()
df_metrics["timestamp"].agg(["min", "max"])
df_metrics["server_id"].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    500 non-null    datetime64[ns]
 1   server_id    500 non-null    category
 2   cpu_pct      500 non-null    float64
 3   memory_pct   500 non-null    float64
 4   response_ms  500 non-null    float64
 5   disk_pct     500 non-null    float64
 6   status       500 non-null    object
dtypes: category(1), datetime64[ns](1), float64(4), object(1)
memory usage: 24.1+ KB

server_id
srv-01    100
srv-02    100
srv-03    100
srv-04    100
srv-05    100
Name: count, dtype: int64

In [18]:
# Task - From describe() output — which server metric has the highest variability (std)? Write your answer as a comment.
df_metrics.describe()

                 timestamp     cpu_pct  memory_pct  response_ms    disk_pct
count                  500  500.000000  500.000000   500.000000  500.000000
mean   2026-01-03 01:30:00   60.027400   63.355000   625.533600   62.412800
min    2026-01-01 00:00:00   20.600000   30.200000    51.800000   30.300000
25%    2026-01-02 00:45:00   39.000000   45.075000   335.950000   46.700000
50%    2026-01-03 01:30:00   60.900000   64.300000   633.700000   62.300000
75%    2026-01-04 02:15:00   81.300000   80.125000   908.125000   78.625000
max    2026-01-05 03:00:00   98.600000   98.000000  1196.400000   94.800000
std                    NaN   23.464233   20.007543   325.294967   18.823192

In [19]:
#statistics per server
df_metrics.groupby("server_id", observed=True)[["cpu_pct", "memory_pct", "response_ms"]].describe()

          cpu_pct                                                        \
            count    mean        std   min     25%    50%     75%   max
server_id
srv-01      100.0  59.640  24.221595  21.8  40.050  60.35  81.550  98.4
srv-02      100.0  59.718  22.960310  20.7  38.825  56.95  80.975  98.2
srv-03      100.0  59.046  23.133161  20.9  41.450  56.70  80.350  98.5
srv-04      100.0  59.928  24.958256  20.6  37.025  61.80  82.900  98.6
srv-05      100.0  61.805  22.332806  20.6  43.775  66.00  80.100  96.7

          memory_pct          ...               response_ms           \
               count    mean  ...     75%   max       count     mean
server_id                     ...
srv-01         100.0  61.871  ...  79.825  96.2       100.0  643.650
srv-02         100.0  65.263  ...  81.575  98.0       100.0  636.718
srv-03         100.0  65.191  ...  83.000  97.3       100.0  613.157
srv-04         100.0  62.149  ...  77.675  97.6       100.0  634.974
srv-05         100.0  62.301  ...  82.625  97.0       100.0  599.169


                  std   min      25%     50%      75%     max
server_id
srv-01     326.831230  51.8  405.350  654.10  913.475  1196.2
srv-02     305.765806  62.5  448.350  615.90  833.600  1196.1
srv-03     318.436634  70.7  333.325  613.85  866.175  1195.8
srv-04     310.422708  89.5  359.100  644.10  913.575  1159.8
srv-05     365.895123  56.4  250.375  619.45  926.400  1196.4

[5 rows x 24 columns]

In [20]:
# CPU breakdown per server
df_metrics.groupby("server_id", observed=True)["cpu_pct"].describe().round(2)

           count   mean    std   min    25%    50%    75%   max
server_id
srv-01     100.0  59.64  24.22  21.8  40.05  60.35  81.55  98.4
srv-02     100.0  59.72  22.96  20.7  38.83  56.95  80.98  98.2
srv-03     100.0  59.05  23.13  20.9  41.45  56.70  80.35  98.5
srv-04     100.0  59.93  24.96  20.6  37.02  61.80  82.90  98.6
srv-05     100.0  61.80  22.33  20.6  43.78  66.00  80.10  96.7

In [21]:
# Memory breakdown per server
df_metrics.groupby("server_id", observed=True)["memory_pct"].describe().round(2)

           count   mean    std   min    25%    50%    75%   max
server_id
srv-01     100.0  61.87  19.77  30.3  44.90  62.65  79.82  96.2
srv-02     100.0  65.26  19.86  30.8  48.62  67.95  81.58  98.0
srv-03     100.0  65.19  20.02  30.6  48.28  65.75  83.00  97.3
srv-04     100.0  62.15  19.06  32.4  47.00  59.15  77.68  97.6
srv-05     100.0  62.30  21.35  30.2  42.08  62.20  82.62  97.0

In [22]:
# Response time breakdown per server
df_metrics.groupby("server_id", observed=True)["response_ms"].describe().round(2)

           count    mean     std   min     25%     50%     75%     max
server_id
srv-01     100.0  643.65  326.83  51.8  405.35  654.10  913.48  1196.2
srv-02     100.0  636.72  305.77  62.5  448.35  615.90  833.60  1196.1
srv-03     100.0  613.16  318.44  70.7  333.32  613.85  866.18  1195.8
srv-04     100.0  634.97  310.42  89.5  359.10  644.10  913.58  1159.8
srv-05     100.0  599.17  365.90  56.4  250.38  619.45  926.40  1196.4

In [24]:
# Task : what percentage of rows in df_metrics have status == "critical". Use value_counts(normalize=True).
df_metrics.value_counts()

timestamp            server_id  cpu_pct  memory_pct  response_ms  disk_pct  status
2026-01-01 00:00:00  srv-01     49.6     94.6        891.8        68.9      ok         1
2026-01-03 17:00:00  srv-05     79.7     38.7        1000.0       80.8      ok         1
2026-01-03 20:00:00  srv-03     32.0     34.2        947.9        59.9      ok         1
                     srv-02     28.3     73.6        298.4        70.3      ok         1
                     srv-01     96.3     59.4        408.6        62.9      ok         1
                                                                                      ..
2026-01-02 08:00:00  srv-02     78.2     93.5        1114.4       59.3      ok         1
                     srv-01     75.9     40.4        712.7        69.4      ok         1
2026-01-02 07:00:00  srv-05     88.9     93.4        699.9        75.3      warning    1
                     srv-04     32.1     69.9        631.8        69.7      ok         1
2026-01-05 03:00:00  srv-05     58.9     69.3        1045.4       93.7      ok         1
Name: count, Length: 500, dtype: int64

In [25]:
df_metrics["status"].value_counts(normalize=True) * 100

status
ok          76.6
warning     17.8
critical     5.6
Name: proportion, dtype: float64

In [27]:
critical_pct = df_metrics["status"].value_counts(normalize=True).get("critical", 0) * 100
print(critical_pct)

5.6000000000000005

['ticket_id', 'server_id', 'category', 'priority', 'created_at', 'resolved_at', 'resolved']

,ticket_id,server_id,category,priority,created_at,resolved_at,resolved
0,INC0001,srv-04,Service Down,2,2026-03-24 02:00:00,NaN,False
1,INC0002,srv-01,CPU High,3,2026-03-19 15:00:00,2026-03-21 12:00:00,True
2,INC0003,srv-03,Service Down,2,2026-04-02 10:00:00,NaN,False
3,INC0004,srv-02,Service Down,1,2026-03-13 20:00:00,NaN,False
4,INC0005,srv-04,Disk Full,2,2026-03-18 09:00:00,2026-03-21 01:00:00,True
...,...,...,...,...,...,...,...
195,INC0196,srv-03,Memory Leak,1,2026-04-04 07:00:00,2026-04-04 17:00:00,True
196,INC0197,srv-02,CPU High,2,2026-03-03 05:00:00,2026-03-03 22:00:00,True
197,INC0198,srv-05,CPU High,2,2026-04-03 20:00:00,2026-04-06 04:00:00,True
198,INC0199,srv-02,Service Down,3,2026-02-10 11:00:00,NaN,False
199,INC0200,srv-05,Disk Full,2,2026-01-02 15:00:00,2026-01-03 11:00:00,True

In [33]:
# Task: Load incidents.csv with correct parse_dates. Find:
# Total number of tickets
# Number of unresolved tickets
# Which category appears most
# Date range of tickets (created_at min and max)

import pandas as pd

# check column names

df_tickets = pd.read_csv("incidents.csv")
print(df_tickets.columns.tolist())

# Load data
df_tickets = pd.read_csv("incidents.csv", parse_dates=["created_at"])

# 1. Total number of tickets
total_tickets = len(df_tickets)

# 2. Number of unresolved tickets
unresolved_tickets = df_tickets["resolved_at"].isna().sum()

# 3. Most common category
most_common_category = df_tickets["category"].value_counts().idxmax()

# 4. Date range (min and max of created_at)
min_date = df_tickets["created_at"].min()
max_date = df_tickets["created_at"].max()

# Print results
print("Total tickets:", total_tickets)
print("Unresolved tickets:", unresolved_tickets)
print("Most common category:", most_common_category)
print("Date range:", min_date, "to", max_date)

['ticket_id', 'server_id', 'category', 'priority', 'created_at', 'resolved_at', 'resolved']
Total tickets: 200
Unresolved tickets: 80
Most common category: CPU High
Date range: 2026-01-01 18:00:00 to 2026-04-10 09:00:00

In [35]:
# Task -  Load app_logs.csv. Find the distribution of log_level values as percentages. Which level appears least?
df_logs = pd.read_csv("app_logs.csv")
print(df_logs)
# Distribution of log_level as percentages
log_dist = df_logs["log_level"].value_counts(normalize=True) * 100

print(log_dist)

# Least frequent log level
least_common = log_dist.idxmin()

print("Least frequent log level:", least_common)

               timestamp server_id log_level                       message  \
0    2026-01-01 07:26:00    srv-04      INFO      Connection timeout error
1    2026-01-01 03:46:00    srv-02      INFO           Database query slow
2    2026-01-08 16:29:00    srv-05     ERROR        CPU threshold exceeded
3    2026-01-04 12:34:00    srv-05   WARNING             Disk usage at 90%
4    2026-01-04 01:25:00    srv-04  CRITICAL         Authentication failed
..                   ...       ...       ...                           ...
295  2026-01-06 11:33:00    srv-02      INFO  Network packet loss detected
296  2026-01-07 19:44:00    srv-02   WARNING           Database query slow
297  2026-01-01 03:35:00    srv-04   WARNING             Disk usage at 90%
298  2026-01-08 03:38:00    srv-01   WARNING        CPU threshold exceeded
299  2026-01-06 11:07:00    srv-02      INFO             Disk usage at 90%

    error_code
0         E004
1         E003
2         E001
3          NaN
4         E002
..         ...
295       E004
296       E003
297       E001
298       E004
299       E002

[300 rows x 5 columns]
log_level
INFO        47.333333
WARNING     25.333333
ERROR       14.666667
CRITICAL    12.666667
Name: proportion, dtype: float64
Least frequent log level: CRITICAL

In [36]:
# Task:  Across all three DataFrames — df_metrics, df_tickets, df_logs — print a summary table showing: DataFrame name, shape, null count total, and date range
import pandas as pd

summary = []

# Helper function
def get_summary(name, df, date_col=None):
    return {
        "DataFrame": name,
        "Shape": df.shape,
        "Total Nulls": df.isna().sum().sum(),
        "Start Date": df[date_col].min() if date_col else None,
        "End Date": df[date_col].max() if date_col else None
    }

# Add summaries (adjust date columns based on your data)
summary.append(get_summary("df_metrics", df_metrics, "timestamp"))
summary.append(get_summary("df_tickets", df_tickets, "created_at"))
summary.append(get_summary("df_logs", df_logs, "timestamp"))

# Convert to DataFrame
df_summary = pd.DataFrame(summary)

print(df_summary)

    DataFrame     Shape  Total Nulls           Start Date             End Date
0  df_metrics  (500, 7)            0  2026-01-01 00:00:00  2026-01-05 03:00:00
1  df_tickets  (200, 7)           80  2026-01-01 18:00:00  2026-04-10 09:00:00
2     df_logs  (300, 5)           49  2026-01-01 00:52:00  2026-01-10 23:49:00